# Generated by Django 3.0 on 2020-11-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeter', '0004_budgeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgeter',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
