# Generated by Django 3.0 on 2020-11-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeter', '0005_auto_20201108_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgeter',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
